### ISSUE TITLE
Problem when trying to login

### ISSUE THREAD

**Issue by driftywinds** [burhan-syed/troddit#195]
Hello, everytime I press the login button on the web app this is the error it shows: - 

![image](https://github.com/user-attachments/assets/91acde33-8713-4334-9f43-cc22d721a22b)

and here are the server logs for the same: - 

```
[next-auth][error][NO_SECRET]
https://next-auth.js.org/errors#no_secret Please define a `secret` in production. MissingSecret [MissingSecretError]: Please define a `secret` in production.
    at assertConfig (/app/node_modules/next-auth/core/lib/assert.js:42:12)
    at AuthHandler (/app/node_modules/next-auth/core/index.js:77:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextAuthApiHandler (/app/node_modules/next-auth/next/index.js:22:19)
    at async NextAuth._args$ (/app/node_modules/next-auth/next/index.js:106:14) {
  code: 'NO_SECRET'
}
```
The README doesn't mention any env variables, so am I missing something?

Here are the contents of my docker compose file: -
```
services:
    troddit:
        container_name: troddit
        ports:
            - 3018:3000
        image: bsyed/troddit
```

**Comment by driftywinds** [comment]
Since the environment variables weren't mentioned in the README, I had to figure them out myself for a working instance through digging into the issues. Here is what it looks like for whoever needs it: - 
```
services:
    troddit:
        container_name: troddit
        ports:
            - 3018:3000
        image: bsyed/troddit
        environment:
            - CLIENT_ID=<Reddit API client ID>
            - CLIENT_SECRET=<Reddit API client secret>
            - REDDIT_REDIRECT=https://troddit.example.com/api/auth/callback/reddit
            - NEXTAUTH_SECRET=<nextauth secret>
            - NEXTAUTH_URL=https://troddit.example.com
            - SIGNING_PRIVATE_KEY=<randomly generated on the terminal>
```
