### ISSUE TITLE
Publish other arch's for dockerimage (Such as amd64)

### ISSUE THREAD

**Issue by Joshndroid** [burhan-syed/troddit#6]
As mentioned in previous issue you have since added docker support and an image to docker hub.
Can you please add amd64 supported image to your dockerhub image repo?

**Comment by cinetube** [comment]
@Joshndroid I have created docker image of troddit for amd64 platforms. Please check the following link 

**Docker Hub:**
```
https://hub.docker.com/r/cinetube/troddit
```

**Docker Compose:**

```
version: '3.3'
services:
    troddit:
        container_name: troddit
        ports:
            - '4087:3000'
        image: cinetube/troddit
```

**Docker Compose (ARM):**

```
version: '3.3'
services:
    troddit:
        container_name: troddit
        ports:
            - '4087:3000'
        image: bsyed/troddit
```
